<?php

namespace Anibalealvarezs\GoogleApi\Services\BusinessPerformance\Enums;

enum DailyMetric: string
{
    case BUSINESS_IMPRESSIONS_DESKTOP_MAPS = 'BUSINESS_IMPRESSIONS_DESKTOP_MAPS';
    case BUSINESS_IMPRESSIONS_DESKTOP_SEARCH = 'BUSINESS_IMPRESSIONS_DESKTOP_SEARCH';
    case BUSINESS_IMPRESSIONS_MOBILE_MAPS = 'BUSINESS_IMPRESSIONS_MOBILE_MAPS';
    case BUSINESS_IMPRESSIONS_MOBILE_SEARCH = 'BUSINESS_IMPRESSIONS_MOBILE_SEARCH';
    case BUSINESS_CONVERSATIONS = 'BUSINESS_CONVERSATIONS';
    case CALL_CLICKS = 'CALL_CLICKS';
    case WEBSITE_CLICKS = 'WEBSITE_CLICKS';
    case DIRECTIONS_REQUESTS = 'DIRECTIONS_REQUESTS';
    case BOOKINGS = 'BOOKINGS';
    case FOOD_ORDERS = 'FOOD_ORDERS';
    case MENU_CLICKS = 'MENU_CLICKS';
}
