# Google
google_client_id: # client_id_string
google_client_secret: # client_secret_string
google_redirect_uri: # https://oauth.pstmn.io/v1/browser-callback
google_refresh_token: # refresh_token_string
google_user_id: # your@email.com

# Slides
slides_scope: # [scope1, scope2]
slides_token: # token_string
slides_themes: # {"SimpleLight2":{"id":"simple-light-2","layouts":{"Cover":"p2","Agenda":"p12","TitleRed":"gc17cfde283_0_16","TitleDiamond":"gc17cfde283_1_2","Text":"gc17cfde283_1_62","Canvas":"gc17cfde283_1_14","CanvasRed":"gc17cfde283_1_68","End":"gc17cfde283_1_76","Creatives":"g118c5aca048_2_0"}}}

# Sheets
sheets_scope: # [scope1, scope2]
sheets_token: # token_string
sheets_themes: # {"SimpleLight2":{"id":"simple-light-2","layouts":{"Cover":"p2","Agenda":"p12","TitleRed":"gc17cfde283_0_16","TitleDiamond":"gc17cfde283_1_2","Text":"gc17cfde283_1_62","Canvas":"gc17cfde283_1_14","CanvasRed":"gc17cfde283_1_68","End":"gc17cfde283_1_76","Creatives":"g118c5aca048_2_0"}}}

# Gmail
gmail_scope: # [scope1, scope2]
gmail_token: # token_string

#Drive
drive_scope: # [scope1, scope2]
drive_token: # token_string

# BigQuery
bigquery_scope: # [scope1, scope2]
bigquery_token: # token_string

# SearchConsole
search_console_scope: # [scope1, scope2]
search_console_token: # token_string
search_console_test_site_url: # https://www.example.com
search_console_test_removable_site_url: # sc-domain:secondary-example.com
search_console_test_sitemap_url: # https://www.example.com/sitemap.xml
search_console_test_removable_sitemap_url: # https://www.example.com/secondary_sitemap.xml
search_console_test_inspect_url: # https://www.example.com/path/to/page
